version: '3'
services:

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./home-assistant/config:/config
      - /data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - "8123:8123"
    network_mode: "host"
    privileged: true
