- id: '1586426754418'
  alias: Reaktor Open Matrix Notification
  description: ''
  trigger:
  - entity_id: binary_sensor.space_open
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Der Reaktor23 ist jetzt offen!
      target: '#reaktor23:reaktor23.org'
    service: matrix.send_message
- id: '1586426842500'
  alias: Reaktor Closed Matrix Notification
  description: ''
  trigger:
  - entity_id: binary_sensor.space_open
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Der Reaktor23 ist geschlossen!
      target: '#reaktor23:reaktor23.org'
    service: matrix.send_message
- id: '1587321324914'
  alias: Powercommander HA Update available
  description: ''
  trigger:
  - entity_id: binary_sensor.updater
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      message: Ich könnte mal wieder ein Update vertragen! Version {{ states.binary_sensor.updater.attributes.newest_version
        }} ist verfügbar!
      target: '#reaktor23:reaktor23.org'
    service: matrix.send_message
- id: '1595319200201'
  alias: Trashwarner
  description: ''
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - tue
  - condition: template
    value_template: '{{ states.sensor.restmull.attributes.remaining == 1 }}'
  action:
  - data:
      message: Morgen ist Müllabfuhr
      title: Müll!
    service: persistent_notification.create
  - data:
      text: Morgen ist Müllabfuhr
    service: rest_command.voiceapi
