- id: '1586426754418'
  alias: Reaktor Open Matrix Notification
  description: ''
  trigger:
  - entity_id: binary_sensor.space_open
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Der Reaktor23 ist jetzt offen!
      target: '#reaktor23:reaktor23.org'
    service: matrix.send_message
- id: '1586426842500'
  alias: Reaktor Closed Matrix Notification
  description: ''
  trigger:
  - entity_id: binary_sensor.space_open
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Der Reaktor23 ist geschlossen!
      target: '#reaktor23:reaktor23.org'
    service: matrix.send_message
- id: '1587321324914'
  alias: Powercommander HA Update available
  description: ''
  trigger:
  - entity_id: binary_sensor.updater
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      message: Ich könnte mal wieder ein Update vertragen! Version {{ states.binary_sensor.updater.attributes.newest_version
        }} ist verfügbar!
      target: '#reaktor23:reaktor23.org'
    service: matrix.send_message
- id: '1595319200201'
  alias: Trashwarner
  description: ''
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - tue
  - condition: template
    value_template: '{{ states.sensor.restmull.attributes.remaining == 1 }}'
  action:
  - data:
      message: Morgen ist Müllabfuhr
      title: Müll!
    service: persistent_notification.create
  - service: matrix.send_message
    data:
      target: '#reaktor23:reaktor23.org'
      message: Hey, morgen ist Müllabfuhr! Wäre nice wenn jemand den Sack an die Strasse
        stellen könnte.
  mode: single
- id: '1602618018034'
  alias: Taster Innenlicht
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.input_6
    to: 'on'
  condition: []
  action:
  - service: script.innenlicht
    data: {}
  mode: single
- id: '1602618109192'
  alias: Taster Aussenlicht
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.input_5
    to: 'on'
  condition: []
  action:
  - service: script.aussenlicht
    data: {}
  mode: single
- id: '1610640499068'
  alias: Update Hackers Counter
  description: Update the number of hacker currently in the Hackerspace
  trigger:
  - platform: time_pattern
    seconds: '5'
  condition: []
  action:
  - service: python_script.hacker_counter
  mode: single
