homeassistant:
  # Name of the location where Home Assistant is running
  name: Reaktor23
  # Location required to calculate the time the sun rises and sets
  latitude: 47.629304
  longitude: 8.262880
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.23.0/24


# Prevent log spamming
logger:
  default: warning
  logs:
    homeassistant.components.mikrotik: warning 
    custom_components.abfallplus: warning
    custom_components.components.rest_command: debug
    homeassistant.components.matrix: debug

# Enables the frontend
frontend:

# Enables configuration UI
config:

api:

python_script:

influxdb:
  host: 192.168.23.11
  include:
    entities:
      - sensor.hackers
      - sensor.zuluft_temperature
      - sensor.sofa_temperature
      - binary_sensor.input_1
      - binary_sensor.input_2
      - binary_sensor.input_3
      - binary_sensor.input_4
      - switch.relay_4
      - switch.relay_3
      

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

recorder:
  #purge_keep_days: 5
  db_url: !secret db_url # database lives on actse
  exclude:
    domains:
      - automation
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date

# input helpers
input_boolean:
input_number:
input_datetime:
input_text:
input_select:

person:

# Allow diagnosing system problems
system_health:

spaceapi: !include spaceapi.yaml

device_tracker: 
        
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
rest_command: !include rest_commands.yaml

matrix:
  homeserver: https://matrix.reaktor23.org
  username: !secret matrix_username
  password: !secret matrix_password
  rooms:
    - "#reaktor23:reaktor23.org"

media_player:
  - platform: mpd
    host: actse

maxcube:
  gateways:
    - host: !secret max_cube_ip 
      port: 62910

corona_landkreis_waldshut:
