binary_sensor.input_1:
  friendly_name: Steckdosen Stromkreis
binary_sensor.input_2:
  friendly_name: Server Stromkreis
binary_sensor.input_3:
  friendly_name: Eltako Innenlicht
  location: Innen
binary_sensor.input_4:
  friendly_name: Eltako Aussenlicht
  location: Aussen
binary_sensor.input_5:
  friendly_name: Taster Aussenlicht
binary_sensor.input_6:
  friendly_name: Taster Innenlicht
switch.relay_1:
  friendly_name: Impuls Aussenlicht
switch.relay_2:
  friendly_name: Impuls Innenlicht
switch.relay_3:
  friendly_name: Ventilation Stufe 2
switch.relay_4:
  friendly_name: Ventilation Stufe 1
sensor.zuluft_temperature:
  location: Zuluftrohr
script.innenlicht:
  location: Innen
sensor.sofa_temperature:
  location: Couch
person.bouni:
  balance: '0'
