restfan_speed_off:
  url: 'http://192.168.23.133/off'
  method: POST
  verify_ssl: false

restfan_speed_1:
  url: 'http://192.168.23.133/speed/1'
  method: POST
  verify_ssl: false

restfan_speed_2:
  url: 'http://192.168.23.133/speed/2'
  method: POST
  verify_ssl: false

restfan_speed_3:
  url: 'http://192.168.23.133/speed/3'
  method: POST
  verify_ssl: false

restfan_oscillation_on:
  url: 'http://192.168.23.133/oscillation/on'
  method: POST
  verify_ssl: false

restfan_oscillation_off:
  url: 'http://192.168.23.133/oscillation/off'
  method: POST
  verify_ssl: false
