- platform: rpi_gpio
  ports:
    19: "Relay 1"
    13: "Relay 2"
    12: "Relay 3"
    6: "Relay 4"
    17: "Relay Circuit 1 On"
    18: "Relay Circuit 1 Off"
    23: "Relay Circuit 2 On"
    27: "Relay Circuit 2 Off"

